#####
# Triggers a production build on Netlify once a commit is tagged with "v*"
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
#####
name: Release production on tag
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@master
      - name: Build
        # See https://github.com/netlify/actions/tree/master/build for details
        uses: netlify/actions/build@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          # this should match previous action `args` until known issue is resolved
          BUILD_DIR: docs
